language: android

env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS=29.0.0

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-$ANDROID_API"
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS"

jdk:
  - oraclejdk8

script: if [[ "$TRAVIS_TAG" ]]; then ./gradlew clean :app:assembleRelease --stacktrace; else ./gradlew clean test --stacktrace; fi

notifications:
  slack: anothericonpack:LAm0AQJq3uPiRGNv53CCrJ5e
  template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.android/build-cache"
    - "$HOME/.m2"
    - "$HOME/.gradle"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

before_script:
  - rm -rf $TRAVIS_BUILD_DIR/app/build/outputs
  - chmod +x gradlew
  
after_script:
  - bash ./telegram_notification.sh
  - chmod +x ./publish_apk.sh; ./publish_apk.sh
